### ISSUE TITLE
Testing and test driven development in JavaScript and Node.js.

### ISSUE THREAD

**Issue by aidanbdh** [sacjs/website#100]
Name: Aidan Harvey
Twitter Handle: aidanharveydev
GitHub Username: aidanbdh
Employer: Freelance
Talk Length: Variable (I can talk about this for hours so however long you need)

---

Title: Testing and test driven development in JavaScript and Node.js
Brief Description: A talk all about testing and test driven development and how it can change your development experience, make you write better code and make your life easier.

**Comment by aidanbdh** [comment]
You can see more specifically what I want to talk about here https://github.com/aidanbdh/sacjs-talk/issues

**Comment by dlindahl** [comment]
Our next few meetups are starting to get booked up. The earliest we'd be able to schedule you would be as a back-up talk for June. Then we take a break for NodeBots Day in July, and then may be back for August depending if our other workshop plans fall apart. September we will definitely fully resume our regular meetups. Are there any dates that you are definitely not available for (we meet the 4th Tuesday of every month)

**Comment by aidanbdh** [comment]
I can do any day! Just let me know if any plans change.

**Comment by dlindahl** [comment]
Hey @aidanbdh, any chance you are free to give this talk for our next meetup on the 27th? We've got a 20min slot to fill. Thanks!

**Comment by dlindahl** [comment]
@aidanbdh cancel that, we were able to find another speaker for the 27th. We'd be interested in having you speak at our July meetup if you are available, however. Please let us know!
