### ISSUE TITLE
Developing Full Stack Applications with Node.js, Angular and NoSQL

### ISSUE THREAD

**Issue by nraboy** [sacjs/website#121]
Name: Nic Raboy & Corbin Crutchley
Twitter Handle: nraboy & crutchcorn
GitHub Username: @nraboy & @crutchcorn
Employer: Couchbase & WireFlare
Talk Length: 1 hour to 1.5 hours depending on what is allowed

---

Title: Developing Full Stack Applications with Node.js, Angular and NoSQL

Brief Description:
In this session, participants will learn how easy it is to develop modular full stack applications where Node.js and NoSQL are used for the API and Angular is used for the client frontend. This is a hands on session where coding along is encouraged.

**Comment by nraboy** [comment]
@sacjs, any update on this?

**Comment by dlindahl** [comment]
Hey, sorry for the late response. We normally don't do hands-on workshops during our regular meetup schedule, but we do have "Summer School" in June/July/August. Would you be interested in running this workshop as part of that segment?

**Comment by nraboy** [comment]
My vision wasn't to have this as a true workshop with labs. More of a watch us demonstrate how easy it is to build an application with these technologies and give people the confidence to try it at home.

What do you think?

**Comment by dlindahl** [comment]
Ah ok, I misunderstood. The "coding along" portion is difficult given our typical setup. We don't have work surfaces for everyone and typing on your lap in a folding chair is not comfortable.

An hour is a bit too long, any chance you could get this done in 45 minutes? Or maybe break this up into two 30min talks? One could focus on API design in Node and NoSQL and the other could focus on interacting with that API with Angular?

In our experience, 45mins is just a lot to ask of people's attention spans :D

**Comment by crutchcorn** [comment]
I've just spoken with @nraboy and we're totally up for two 30 minute talks with mine (Angular) being based on @nraboy's (the API). Should I open a new issue for my talk or would it be possible to coordinate both in this issue?

**Comment by dlindahl** [comment]
Nah, no reason to break the issues up. All I need is some catchy titles for both pieces.

When it comes to writing the material, I'd suggest keeping them as atomic as possible to keep things engaging (if that makes sense)

**Comment by crutchcorn** [comment]
After thinking all day of various puns, we have settled on the two talk names:
`Express yourself with Node; NoSQL needed` - @nraboy 
And
`Smooth sailing with Angular` - Me

I'll likely mention that the API is in reference to another talk, but will try to write my talk so that you don't necessarily have to see the other talk (which is fairly simple to do by defining types in classes from the API ahead of time)

**Comment by nraboy** [comment]
@dlindahl What dates did you have in mind for this?

@crutchcorn isn't available on Tuesdays and Thursdays because of school. I'm pretty open, but it'd be best to have it with a month of notice so we can help you promote it.

Let us know what you're thinking.

Best,

**Comment by dlindahl** [comment]
We have one 30 minute slot available on March 27 so if you want, we can get you on this month @nraboy. Not sure what to do about @crutchcorn's schedule since we've been doing Tuesdays for the last three years. Any chance we can find a hole in your schedule in the future so we can slot you in?

**Comment by crutchcorn** [comment]
I've just confirmed that I am able to take a day from my class schedule in order to do the talk. What days are open?

**Comment by nraboy** [comment]
Tuesday March 27 works for me. @crutchcorn does that work for you?

**Comment by crutchcorn** [comment]
I wouldn't be able to make it on the 27th but we could communicate about your talk since it seems like there's only one session opening and I could do my half of the talk on a different day

**Comment by dlindahl** [comment]
If April 24th works for both of you, we can do it then. Sound good?

**Comment by nraboy** [comment]
Talked to @crutchcorn, April 24th works for both of us. I am going to add it to my calendar.

Can you send us the Meetup link when you post it so we can promote it?

Thanks,

**Comment by nraboy** [comment]
Hey @dlindahl can you lock us in and get us on the Meetup calendar?

**Comment by nraboy** [comment]
Hey @dlindahl, just checking in on this

**Comment by dlindahl** [comment]
Yep, we're good for April. I'll make the requisite updates

**Comment by dlindahl** [comment]
Only extra bit I need is a description for the two talks for the website

**Comment by nraboy** [comment]
Hey @dlindahl,

How about this description for my 30 minute session:

In this session, participants will learn how to create a RESTful API with CRUD endpoints using the Hapi.js JavaScript framework for Node.js and the open source NoSQL database, Couchbase. We'll explore everything from key-value operations to rich querying of JSON data with SQL, yielding results that can be easily applied towards any client facing front-end application.

I'll let @crutchcorn add his part two to the mix.

**Comment by crutchcorn** [comment]
Sorry for the delay - just moved into my new place.

My 30 minute session can have this as the description:

Ever wondered how to create an Angular webapp that efficiently communicates with a NoSQL backend? We'll cover the basics such as routing, HttpClient listeners, and more! We'll even PWA-ify the place up! If you're curious how to structure your Angular application, allowing future growth and expansion, or even just want to dip your toes into the framework to see how to do things - this is the talk for you!

**Comment by dlindahl** [comment]
Perfect! Its live up on https://www.sacjs.com/events/2018-04-24-monthly-meetup/

I'll get it into Meetup.com soon-ish

**Comment by nraboy** [comment]
Just checking in to see if you had a chance to update the Meetup.com site.

**Comment by dlindahl** [comment]
@nraboy Meetup has been announced!

https://www.sacjs.com/events/2018-04-24-monthly-meetup/
https://www.meetup.com/The-Sacramento-Javascript-Meetup/events/247295930/

**Comment by nraboy** [comment]
Awesome!

Thanks Derek!
