### ISSUE TITLE
Layout | CSS Grid

### ISSUE THREAD

**Issue by ImJohnDoe** [sacjs/website#124]
Name: Roman Pshichenko
GitHub Username: imjohndoe
Employer: Infinite Technologies Inc.
Talk Length: 20 minutes

Title: Layout | CSS Grid
Brief Description:
CSS was not meant to handle layouts until now. Be it backend, front end or full stack, this is a serious problem that many developers face. Without using using a framework like bootstrap we will layout some sample UI  to help us understand the difference between styles, flex and grid.

CSS has recently gotten a power-up. Don’t be scared, get excited.

**Comment by dlindahl** [comment]
@ImJohnDoe Are you available to give this talk during our meetup on September 25?

**Comment by ImJohnDoe** [comment]
Hi Derek, im sorry for the delayed response. I can present on this topic on the 25th.

**Comment by a-axton** [comment]
@ImJohnDoe Sorry we didn't get you in last meetup. Are you available to give this talk at our next meetup October 23rd?

**Comment by ImJohnDoe** [comment]
@a-axton Id be happy to.

**Comment by a-axton** [comment]
Awesome, look forward to it!

**Comment by a-axton** [comment]
Thanks for coming!
