### ISSUE TITLE
Realtime browser playback of a motion-tracked image plane over a video, using After Effects, Three.js, and React.

### ISSUE THREAD

**Issue by jonjahr** [sacjs/website#125]
Twitter Handle: @jonjahr
GitHub Username: @jonjahr
Employer: Meringcarson
Talk Length: 30 minutes

---

Title: Realtime browser playback of a motion-tracked image plane over a video, using After Effects, Three.js, and React.

Brief Description: Postmortem of a recent project where I learned how to composite a motion-tracked image plane over pre-recorded video in the browser.   Specifically, I recorded a video of a laptop on a desk, did a 3D motion track in After Effects, converted the keyframes to JSON, and used the keyframes to composite a 3D image plane over the video of the laptop that matched the laptop movement.  In this realtime-rendered setup, we can dynamically insert any object into the laptop screen that we want.  I used this to create a homepage slideshow for a React website.  I can walk through the project as high- or low-level as you like.

**Comment by a-axton** [comment]
I'm closing older proposals, if you're still interested in doing this talk let me know and I can re-open
