### ISSUE TITLE
Introduction to animated page transitions in React with GreenSock

### ISSUE THREAD

**Issue by jonjahr** [sacjs/website#126]
Twitter Handle: jonjahr
GitHub Username: jonjahr
Employer: MeringCarson
Talk Length: 30 minutes
---
Title: Introduction to animated page transitions in React with GreenSock

Brief Description: You're making a React Single-Page App.  You want animated page transitions.  You found `react-transition-group` and `CSSTransition`, but that doesn't quite satisfy your appetite for animation.  You want the power and flexibility of GreenSock and TimelineMax.  And nobody seems to be doing it yet (or maybe I'm just searching the wrong keywords).  This talk is a walkthrough of the gotchas and frustrations I encountered, and a solution that worked great for me: a `GSAPTransition` component I made that makes GSAP transitions possible with as few as two simple props.

**Comment by a-axton** [comment]
I'm closing older proposals, if you're still interested in doing this talk let me know and I can re-open
