### ISSUE TITLE
Talk Proposal | Geospatial Applications created using JavaScript (and NoSQL)

### ISSUE THREAD

**Issue by masyukun** [sacjs/website#127]
Name: Matthew Royal
Twitter Handle: @masyukun
GitHub Username: masyukun
Employer: MarkLogic Corporation
Talk Length: 30 mins

---

Title: Geospatial Applications created using JavaScript (and NoSQL)

Brief Description: Matthew Royal will demonstrate the Geophoto web application, that ingests georeferenced image data into JSON EXIF documents and RDF triple graph data to display on a map, and link with other datasets. Geophoto is an open source project on GitHub, built with an AngularJS frontend, a Node.JS middle tier, and communicates with the MarkLogic backend through a server-side JS REST API. We will use JavaScript and SPARQL to explore the data.

Bio: Matthew is a software consultant, and has been working with JS and living in Sacramento since 2013. He builds enterprise data systems and applications for clients using an increasing number of JS-based tools.

**Comment by a-axton** [comment]
I'm closing older proposals, if you're still interested in doing this talk let me know and I can re-open
