### ISSUE TITLE
Talk Proposal: Tink, Plug n Play, what about my way?

### ISSUE THREAD

**Issue by soldair** [sacjs/website#128]
Name: Ryan Day
Twitter Handle: soldair
GitHub Username: soldair
Employer: google
Talk Length: 10-20

---

### Title: 
Tink , Plug n Play, what about my way?

### Brief Description:  
Both yarn and npm in a feat of simultaneous invention have brought us new patterns to store and resolve your dependencies without node_modules. 
I'm going to talk about trade offs, interesting implementation details, and considerations for making your own install-less dependency installer for node. 
Maybe we'll use a custom loader to reduce startup time for a node application!

**Comment by a-axton** [comment]
Hey @soldair! Thanks for submitting a proposal. Are you available to give this talk at our next meetup on Oct 23rd?

**Comment by soldair** [comment]
sure =)
see y'all there

**Comment by a-axton** [comment]
Great! We'll be pairing you with a talk on CSS grid which should be around 20 minutes. See you then!
