### ISSUE TITLE
Talk Proposal: React Hooks 

### ISSUE THREAD

**Issue by crutchcorn** [sacjs/website#130]
Name: Corbin Crutchley
Twitter Handle: crutchcorn
GitHub Username: crutchcorn
Employer: Linkd Inc. (I do not represent them in any way in this talk)
Talk Length: 30mins

---

Title: Reeling you in on React Hooks
Brief Description: An introduction to React Hooks; what they are, why you'd want to use them, and how to add them to a project today*. Knowing a bit about React will help you here, but is not maditory to understand.

*And why you shouldn't yet

**Comment by a-axton** [comment]
Hey Corbin, I know it's been a while since you submitted this but would you be available to speak at our next meetup? We'll be having it next Tuesday on the 23rd

**Comment by crutchcorn** [comment]
I very much can!

**Comment by a-axton** [comment]
Awesome! Thank you for the quick reply! Looking forward to it.

**Comment by a-axton** [comment]
Thanks Corbin, awesome talk!
