### ISSUE TITLE
Talk proposal: JS Testing with Mocha

### ISSUE THREAD

**Issue by drnugent** [sacjs/website#132]
Name: Christopher Hiller
Twitter Handle: @b0neskull
GitHub Username: boneskull
Employer: IBM
Talk Length: 30m

---

Title: JS Testing with Mocha
Brief Description: I start real basic; some testing terminology, then show how to get started from scratch with Mocha.  I have some example code (Express middleware) which I then describe how to write unit and integration tests for (and run them)

**Comment by boneskull** [comment]
Hi :wave: this is my talk; I'm looking to book travel and was wondering if there was any update?

**Comment by a-axton** [comment]
Hey @boneskull, sorry for the really late reply but are you still interested in giving this talk? We just started having meetups again and our next one is on the 28th

**Comment by a-axton** [comment]
I'm closing older proposals, if you're still interested in doing this talk let me know and I can re-open
