### ISSUE TITLE
Talk Proposal : DECK.GL and building Geospatial data visualization web apps

### ISSUE THREAD

**Issue by nharrisanalyst** [sacjs/website#133]
Name: Nathan Harris
Twitter Handle: nathaniharris
GitHub Username: nharrisanalyst
Employer: Freelance Data Visualiation Dveloper
Talk Length: 20min

---

Title: DECK.GL and building Geospatial data visualization web apps
Brief Description:
DECK.GL is a WebGL-powered framework for visual exploratory data analysis of large datasets.
I introduce WebGL and talk about how it can be used for data visualizations and process large amounts of data (from uber data). Then I introduce DECK.GL its layered approach and how it works with react.
Then I show how it can be used with mapbox and in an application.

examples
me: https://gun-viz.herokuapp.com/
others:http://deck.gl/#/examples/core-layers/hexagon-layer

**Comment by a-axton** [comment]
@nharrisanalyst Hey Nathan, would you be willing to give this talk at our next meet up on April 23rd?

**Comment by nharrisanalyst** [comment]
I couldn't give it this month I just relocated to the Bay Area but I am 90% sure I could give it the following month.

**Comment by a-axton** [comment]
Our next meetup is on the 28th, are you available to speak then?

**Comment by nharrisanalyst** [comment]
yeah I could do it then

**Comment by a-axton** [comment]
Awesome! I'll put you down for it

**Comment by nharrisanalyst** [comment]
Ok sounds good but my employer is now Plume LLC

**Comment by a-axton** [comment]
thanks for speaking Nathan, DECK.GL is freaking awesome
