### ISSUE TITLE
No More meetups??

### ISSUE THREAD

**Issue by nharrisanalyst** [sacjs/website#135]
Why are there no more meetups this community helped me when I was learning JS and educated me to where I am now and seeing it die saddens me I know we have speakers and people would attend if we held meetups. 
There is always a tech recruiter or two that will sponsor?
So what is stopping the meetups??

**Comment by a-axton** [comment]
We skipped one or two because we were busy and then I don't know... it just kind of happened. Thanks for saying something, it's helped get us motivated to start them up again. I'm hoping to resume them next month

**Comment by nharrisanalyst** [comment]
cool sorry I did this but I started coming to this meetings before I was a professional several years ago and now I work full time in Javascript and getting together really helped me stay motivated and get educated. So it would be hard to see them go away.

**Comment by a-axton** [comment]
No need to apologize 🙂 I'm glad our meetings were helpful to you, hopefully we can reboot them and help even more people out!
