### ISSUE TITLE
Talk proposal: Communication Skills for Technical & Creative Professionals

### ISSUE THREAD

**Issue by thefatpanther** [sacjs/website#136]
This talk delves into adding business analysis and communications skills into the toolbox of technical professionals such as graphic artists, software engineers, database administrators and DevOps Engineers. We will talk about how to add value during the discovery process, the art of asking questions, working alongside business analysts and how end-to-end documentation builds better products today and in the future.

**Comment by a-axton** [comment]
Can't wait!

**Comment by efletch** [comment]
What date will this talk be? I don't see anything listed on the SacJS Meetup Group yet https://www.meetup.com/The-Sacramento-Javascript-Meetup/

I want to share it with some coworkers 😄

**Comment by a-axton** [comment]
Tuesday, April 23rd. Posting should be up soon

**Comment by a-axton** [comment]
Thanks for speaking Mark, really enjoyed it. Made me realize how much I can improve my communication and how important it is
