### ISSUE TITLE
Talk Proposal: Tableau Javascript API and D3 integration

### ISSUE THREAD

**Issue by mantsui** [sacjs/website#137]
Name: Man Tsui
Employer: UC Davis Health
Talk Length: 30 min

Title: Tableau Javascript API and D3 integration
Custom data visualization on top of Tableau with popular open-source API like D3.js, 
reveal.js, and etc.

Good starting point to lead to Tableau Extension API

Examples:
https://mantsui.github.io/Tableau_D3_Sunburst_MedicareIP
https://mantsui.github.io/Tableau_Portfolio_01
https://mantsui.github.io/Tableau_D3_Treemap_MedicareOP

**Comment by a-axton** [comment]
Thanks for submitting, Man!

**Comment by a-axton** [comment]
Hi Man, I'm going to go with the other proposal this month because our last talk was similar to your topic. Are you open to giving it at future meetups?

**Comment by mantsui** [comment]
Sure, no problem. I can give it at future meetups.
