### ISSUE TITLE
Talk Proposal: Lessons in Electron Development

### ISSUE THREAD

**Issue by tnishimura** [sacjs/website#138]
Name: Toshiro Nishimura
Twitter Handle:
GitHub Username: tnishimura
Employer: Independent
Talk Length: 20+ minutes, flexible

---

Title: Lessons in Electron Development
Brief Description:

Electron is the thing that bundles a webapp and browser into a desktop app, right? Well, yes, but the devils are in the details. In this talk, I'll go over some of the things I've learned over a full year of developing a commercial desktop app with Electron, including:

- Electron architecture, the basics
- Workflow is DIY
- Security is not free
- Cross platforming is not free
- I hate Code signing and so will you
- Frameworks will fight you
- IPC is worth investing in
- and maybe more

**Comment by a-axton** [comment]
Thanks for submitting the proposal, looks awesome!
