### ISSUE TITLE
Talk Proposal: Design Systems with Diez

### ISSUE THREAD

**Issue by taylorpoe** [sacjs/website#140]
Name: Taylor Poe
Twitter Handle: @taylorpoe
GitHub Username: @taylorpoe
Employer: Haiku
Talk Length: 25 minutes

---- 

Title: Unify your design language

In this talk we'll explain why having a design system can help your team and products, regardless of scale. We'll also demo https://diez.org — a new design system framework that makes it easy to adopt a unified design language across codebases and platforms. With Diez you use TypeScript to compose deeply customizable, reusable, and developer-friendly design token components that become compiled into pure native SDKs for iOS, Android, and the Web.

**Comment by a-axton** [comment]
Sorry for taking so long to accept! Are you still available to speak on the 23rd?

**Comment by a-axton** [comment]
Accepted for 8/27 meetup, thanks!

**Comment by taylorpoe** [comment]
I'll plan on it! Thanks!
