### ISSUE TITLE
Talk Proposal: Angular Templates — From Start to Source

### ISSUE THREAD

**Issue by crutchcorn** [sacjs/website#141]
Name: Corbin Crutchley

Twitter Handle: @crutchcorn

GitHub Username: @crutchcorn

Employer: Hilton (I do not reflect their views)

Talk Length: 30min-1hr (up to you!)

---

Title: Angular Templates — From Start to Source

Brief Description: 
In this talk, we’ll explain what templates are, how they relate to views, and how Angular uses them inside it’s own source code (including reading some of its source!). Because this talk is a deeper dive into Angular, it's suggested you do a quick once-through on their "Getting Started" docs.

I won't be able to give this talk until after August 9th (due to other events on my end)

**Comment by crutchcorn** [comment]
This talk has an associated blog post here:

https://unicorn-utterances.com/posts/angular-templates-start-to-source/

And generally follows (admittedly much more info on the blog post) the same structure as the post

**Comment by a-axton** [comment]
Hey @crutchcorn , sorry for the late notice but would you like to give this talk at our next meetup (Oct 22nd)?

**Comment by crutchcorn** [comment]
I sure can

**Comment by crutchcorn** [comment]
Event still says TBH on meetup? Are we able to change that?

**Comment by a-axton** [comment]
Thanks! I will get on that ASAP and announce it
