### ISSUE TITLE
Deno, a better Node

### ISSUE THREAD

**Issue by nbunneysky** [sacjs/website#142]
Name: Nate Bunney

Twitter Handle: @nbunney

GitHub Username: @nbunney

Employer: Skyslope.com

Talk Length: 45min-1hr

Title: Deno, a better Node

- Why Deno
- Difference from Node.js
  - Better Security
  - Better Module System
  - Multi-Threaded
  - Typescript Baked In - Brief talk (10 mins) on Typescript and why it is a good addition
- Demo of Deno - Start with a "mostly there" file and add in the necessary bits to make a simple API.

**Comment by a-axton** [comment]
Thanks again Nate!
