### ISSUE TITLE
Abhi Aiyer: GraphQL + Apollo + You

### ISSUE THREAD

**Issue by abhiaiyer91** [sacjs/website#99]
Name: Abhi Aiyer
Twitter Handle: abhiaiyer
GitHub Username: abhiaiyer91
Employer: Workpop
Talk Length: 30mins

---

Title: GraphQL + Apollo + You
Brief Description:
In this talk Abhi will explain how REST apis are things of the past and how GraphQL is positioning itself to be the replacement to your current Data Layer. A contributor to a suite of GraphQL tools called Apollo, Abhi will walk through the concepts of GraphQL along with Caching Clients for your Front End.

**Comment by abhiaiyer91** [comment]
Just moved to SAC from LA, would love to share my experience with you all!

**Comment by dlindahl** [comment]
We'd love to have you! Our next few meetups are starting to get booked up. The earliest we'd be able to schedule you would be as a back-up talk for June. Then we take a break for NodeBots Day in July, and then may be back for August depending if our other workshop plans fall apart. September we will definitely fully resume our regular meetups. Are there any dates that you are definitely not available for (we meet the 4th Tuesday of every month)

**Comment by abhiaiyer91** [comment]
September sounds great! Can you book me in.

**Comment by dlindahl** [comment]
Hi @abhiaiyer91, would you be available to talk next week on the 27th?

**Comment by dlindahl** [comment]
@abhiaiyer91 cancel that, we were able to find another speaker for the 27th. We'd be interested in having you speak at our July meetup if you are available, however. Please let us know!
